AKS-Cluster hinzugefügt | Key-Vault ergänzt
FAP-Cloud-Service/FAP-Infrastructure pull request #19
Opened 2021-04-25 19:35 UTC by leonschbbht

Kubernetes Cluster hinzugefügt. Die Einstellungen sind aktuell noch sehr Basic.
Das Cluster kann bei bedarf zwischen 1er und 3 VM's mit je 2 Pods skallieren.

Die Secrets des Clusters werden in einem Azure Key Vault hinterlegt. 

Closes #7.

2021-04-26 14:51 UTC, maltemorgenstern requested changes

2021-04-26 14:51 UTC, maltemorgenstern commented on infrastructure/functions/main.tf
> -  tags     = var.azure_tags
Hier ist beim merge was kaputt gegangen, oder?

2021-04-26 14:51 UTC, maltemorgenstern commented on infrastructure/functions/main.tf
> -  tags                     = var.azure_tags
Hier ist beim merge was kaputt gegangen, oder?

2021-04-26 14:51 UTC, maltemorgenstern commented on infrastructure/functions/main.tf
> -  tags                = var.azure_tags
Hier ist beim merge was kaputt gegangen, oder?

2021-04-26 14:51 UTC, maltemorgenstern commented on infrastructure/functions/output.tf
> +}
Ich weiß nicht, was hier best practise ist, aber ein Vorschlag:
Statt die resource_group, in der alle Sachen liegen, im functions modules zu erstellen und dann rauszureichen, könnte man sie doch auch in einer der main.tfs (root oder infrastructure/main.tf) erstellen und dann reinreichen - dann löst man sie von den functions.

2021-04-26 14:51 UTC, maltemorgenstern commented on infrastructure/secrets/variables.tf
> +variable "azure_user" {
Eventuell könnte man das "azure_users" nennen - dann wird klar, dass hier mehrere Nutzer vorliegen (nur Kosmetik)

2021-04-26 14:51 UTC, maltemorgenstern commented on .terraform.lock.hcl
>      "zh:3cd456047805bf639fbf2c761b1848880ea703a054f76db51852008b11008626",
Random scheint immer noch nicht weg zu sein 😞

2021-04-27 19:56 UTC, leonschbbht commented on .terraform.lock.hcl
>      "zh:3cd456047805bf639fbf2c761b1848880ea703a054f76db51852008b11008626",
Eine Möglichkeit wäre noch, dass es am state selbst liegt. Da kann man ggf. mit dem CLI Abhilfe schaffen, die Priorität dafür ordne ich aktuell aber als "eher gering" ein 👎🏼

2021-04-27 19:56 UTC, leonschbbht commented
Bis auf den Random Provider habe ich die Punkte einarbeiten können 👍🏼

2021-04-28 17:40 UTC, maltemorgenstern requested changes
Wenn die resource_group reingereicht wird, darf der Name meines Erachtens nach nicht mehr genutzt werden.

2021-04-28 17:40 UTC, maltemorgenstern commented on infrastructure/functions/main.tf
> +  resource_group_name = var.prod_resource_group.fap-backend-resource-group.name
```suggestion
  resource_group_name = var.prod_resource_group.name
```

2021-04-28 17:40 UTC, maltemorgenstern commented on infrastructure/functions/main.tf
> +  resource_group_name        = var.prod_resource_group.fap-backend-resource-group.name
```suggestion
  location                   = var.prod_resource_group.location
  resource_group_name        = var.prod_resource_group.name
```

2021-04-28 17:40 UTC, maltemorgenstern commented on infrastructure/main.tf
> +  name     = "fap-backend-application"
```suggestion
resource "azurerm_resource_group" "fap-prod-resource-group" {
  name     = "fap-prod-application"
```

2021-04-28 17:40 UTC, maltemorgenstern commented on infrastructure/main.tf
> +  prod_resource_group    = azurerm_resource_group.fap-backend-resource-group
```suggestion
  prod_resource_group    = azurerm_resource_group.fap-prod-resource-group
```

2021-04-28 17:40 UTC, maltemorgenstern commented on infrastructure/main.tf
> +  prod_resource_group = azurerm_resource_group.fap-backend-resource-group
```suggestion
  prod_resource_group = azurerm_resource_group.fap-prod-resource-group
```

2021-04-28 17:40 UTC, maltemorgenstern commented on infrastructure/main.tf
> +  prod_resource_group = azurerm_resource_group.fap-backend-resource-group
```suggestion
  prod_resource_group = azurerm_resource_group.fap-prod-resource-group
```

2021-04-28 18:13 UTC, maltemorgenstern approved these changes
Man könnte noch den Formatter auf allen Dateien laufen lassen, aber das ist auch nicht kriegsentscheidend.

LGTM 👍

2021-04-29 06:12 UTC, merged