Feature/add terraform project
FAP-Cloud-Service/FAP-Infrastructure pull request #8
Opened 2021-04-20 19:22 UTC by leonschbbht

2021-04-20 19:22 UTC, leonschbbht commented
closes #8

2021-04-20 19:30 UTC, maltemorgenstern requested changes
Ich habe ein paar Anmerkungen bzgl. Namensgebung und Verständnis dagelassen.

2021-04-20 19:30 UTC, maltemorgenstern commented on variables.tf
> +  description = "Array of names for azure-resource-Group"
```suggestion
  description = "Array of names for azure-resource-group"
```

2021-04-20 19:30 UTC, maltemorgenstern commented on infrastructure/functions/variables.tf
> +variable "azure_resource_groups" {}
Welchen Zweck hat es, die Variable bis hier reinzureichen? Die wird doch nicht benutzt, oder?

2021-04-20 19:30 UTC, maltemorgenstern commented on infrastructure/functions/main.tf
> +}
Welchen Hintergrund haben die resource names?
Die wechseln so komplett zwischen "fap-", "fap-application-", "backend-" und "backend-application-".

Kann man das nicht vereinheitlichen, z.B. "fap-backend-[resource_type]", also z.B. "fap-backend-function-app"?

2021-04-20 19:30 UTC, maltemorgenstern commented on README.md
> +Für die Ausführung der Terraform-Konfiguraiton muss die Installierte Version `>= 0.14 sein`
```suggestion
Für die Ausführung der Terraform-Konfiguraiton muss die installierte Version `>= 0.14` sein.
```

2021-04-20 19:32 UTC, leonschbbht commented on infrastructure/functions/variables.tf
> +variable "azure_resource_groups" {}
Die Idee ist es, ein Array reinzureichen. Falls wir eine Testumgebung haben wollen müssen wir nur ein "for_each" bei der RG ergänzen.

2021-04-21 16:39 UTC, maltemorgenstern approved these changes
LGTM 👍

2021-04-21 16:53 UTC, merged